quarkus:
  smallrye-graphql:
    events:
      enabled: true
  http:
    port: 8080
  datasource:
    devservices:
      enabled: false     # disables Quarkus devServices, including Docker

#ebean:
#  dbSchema: my_app      # use this schema rather than public
#  migration:
#    run: true           # run database migrations on startup
#  ddl:
#    generate: true
#    run: true

datasource:
  db:
    username: portal
    password: portal
    url: jdbc:postgresql://localhost:30002/graphql
    databaseDriver: org.postgresql.Driver